[package]
name = "chimitheque_utils"
version = "0.1.0"
edition = "2024"
authors = ["Thomas Bellembois <thomas.bellembois@proton.me>"]
description = "Chemical utilities for Chimithèque"
license = "GPL-3.0"
repository = "https://github.com/tbellembois/chimitheque_utils"
homepage = "https://github.com/tbellembois/chimitheque_utils"
readme = "README.md"
categories = ["database", "science"]
keywords = ["chemistry", "biology", "database", "management"]
rust-version = "1.88.0"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
# unwrap_used = "warn"
# expect_used = "warn"
# panic = "warn"
# unreachable = "warn"

missing_errors_doc = "allow"
missing_panics_doc = "allow"
struct_excessive_bools = "allow"
too_many_lines = "allow"

[dependencies]
env_logger = { version = "0.11.10", default-features = false }
log = { version = "0.4.29", default-features = false }
regex = { version = "1.13.1", default-features = false }

chimitheque_defines = { git = "https://github.com/tbellembois/chimitheque_defines.git", branch = "main" }

[patch."https://github.com/tbellembois/chimitheque_defines.git"]
chimitheque_defines = { path = "/home/tbellembois/workspace/workspace_rust/chimitheque_defines" }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(tarpaulin_include)'] }
